version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1

    steps:
      - checkout

      # Composer
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
      - run:
          name: Installing Composer Packages
          command: composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      # Xdebug
      - run:
          name: Getting Xdebug Enabled
          command: sudo docker-php-ext-enable xdebug

      # PHP Unit
      - run:
          name: Running Unit Tests
          command: ./vendor/bin/phpunit --coverage-html=/tmp/coverage

      - store_artifacts:
          path: /tmp/coverage
